"""add insurance age and rates

Revision ID: 455f8d629913
Revises: 86369419f544
Create Date: 2026-07-13 17:25:31.692343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '455f8d629913'
down_revision: Union[str, Sequence[str], None] = '86369419f544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_products', sa.Column('age', sa.String(length=50), nullable=True))
    op.add_column('insurance_products', sa.Column('male_insurance_rate', sa.String(length=50), nullable=True))
    op.add_column('insurance_products', sa.Column('female_insurance_rate', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurance_products', 'female_insurance_rate')
    op.drop_column('insurance_products', 'male_insurance_rate')
    op.drop_column('insurance_products', 'age')
    # ### end Alembic commands ###
