"""add watchlist categories

Revision ID: 53d66f7337b7
Revises: 76458807650c
Create Date: 2026-06-23 15:10:56.958329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d66f7337b7'
down_revision: Union[str, Sequence[str], None] = '76458807650c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. 관심종목 카테고리 테이블 생성
    op.create_table(
        "stock_watchlist_categories",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("category_name", sa.String(length=100), nullable=False),
        sa.Column("display_order", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "category_name", name="uk_watchlist_category_user_name"),
    )

    # 2. stock_watchlists에 category_id 추가
    op.add_column(
        "stock_watchlists",
        sa.Column("category_id", sa.BigInteger(), nullable=False),
    )

    # 3. 기존 외래키가 의존할 수 있는 일반 인덱스를 먼저 생성
    op.create_index(
        "ix_stock_watchlists_user_id",
        "stock_watchlists",
        ["user_id"],
        unique=False,
    )

    op.create_index(
        "ix_stock_watchlists_stock_id",
        "stock_watchlists",
        ["stock_id"],
        unique=False,
    )

    op.create_index(
        "ix_stock_watchlists_category_id",
        "stock_watchlists",
        ["category_id"],
        unique=False,
    )

    # 4. 이제 기존 unique index 삭제
    op.drop_index("uk_watchlist_user_stock", table_name="stock_watchlists")

    # 5. category_id 외래키 추가
    op.create_foreign_key(
        "fk_stock_watchlists_category_id",
        "stock_watchlists",
        "stock_watchlist_categories",
        ["category_id"],
        ["id"],
    )

    # 6. 새 unique 제약조건 추가
    op.create_unique_constraint(
        "uk_watchlist_user_category_stock",
        "stock_watchlists",
        ["user_id", "category_id", "stock_id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_watchlists', type_='foreignkey')
    op.drop_constraint('uk_watchlist_user_category_stock', 'stock_watchlists', type_='unique')
    op.create_index(op.f('uk_watchlist_user_stock'), 'stock_watchlists', ['user_id', 'stock_id'], unique=True)
    op.drop_column('stock_watchlists', 'category_id')
    op.drop_table('stock_watchlist_categories')
    # ### end Alembic commands ###
