"""update financial product rate tables

Revision ID: 54aae840dcb3
Revises: 5faf485c136b
Create Date: 2026-07-02 16:02:03.831765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '54aae840dcb3'
down_revision: Union[str, Sequence[str], None] = '5faf485c136b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit_product_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('base_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('max_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('rate_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['deposit_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saving_product_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('base_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('max_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('rate_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['saving_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('deposit_products', 'join_period')
    op.drop_column('deposit_products', 'interest_rate')
    op.drop_column('deposit_products', 'max_rate')
    op.alter_column('financial_product_recommendations', 'product_type',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('financial_product_recommendations', 'recommendation_reason',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('insurance_products', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.add_column('interest_calculation_histories', sa.Column('before_tax_interest', sa.BigInteger(), nullable=False))
    op.add_column('interest_calculation_histories', sa.Column('after_tax_interest', sa.BigInteger(), nullable=False))
    op.drop_column('interest_calculation_histories', 'before_tax_amount')
    op.drop_column('interest_calculation_histories', 'after_tax_amount')
    op.drop_column('saving_products', 'join_period')
    op.drop_column('saving_products', 'interest_rate')
    op.drop_column('saving_products', 'max_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saving_products', sa.Column('max_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('saving_products', sa.Column('interest_rate', mysql.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('saving_products', sa.Column('join_period', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('interest_calculation_histories', sa.Column('after_tax_amount', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.add_column('interest_calculation_histories', sa.Column('before_tax_amount', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.drop_column('interest_calculation_histories', 'after_tax_interest')
    op.drop_column('interest_calculation_histories', 'before_tax_interest')
    op.alter_column('insurance_products', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('financial_product_recommendations', 'recommendation_reason',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('financial_product_recommendations', 'product_type',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.add_column('deposit_products', sa.Column('max_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('deposit_products', sa.Column('interest_rate', mysql.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('deposit_products', sa.Column('join_period', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_table('saving_product_rates')
    op.drop_table('deposit_product_rates')
    # ### end Alembic commands ###
