"""add agent chat tables

Revision ID: 696816428afc
Revises: 54aae840dcb3
Create Date: 2026-07-10 10:24:56.262973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '696816428afc'
down_revision: Union[str, Sequence[str], None] = '54aae840dcb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_chat_sessions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('chat_type', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_chat_sessions_user_id'), 'agent_chat_sessions', ['user_id'], unique=False)
    op.create_table('agent_chat_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('used_tools', sa.Text(), nullable=True),
    sa.Column('referenced_summary_id', sa.BigInteger(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['referenced_summary_id'], ['monthly_spending_summaries.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['agent_chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_chat_messages_session_id'), 'agent_chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_chat_messages_user_id'), 'agent_chat_messages', ['user_id'], unique=False)
    op.drop_table('overspending_items')
    op.alter_column('card_statements', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('card_statements', 'uploaded_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('card_statements', 'processed_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('card_statements', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_index(op.f('ix_card_statements_id'), 'card_statements', ['id'], unique=False)
    op.drop_index(op.f('ix_stock_watchlists_category_id'), table_name='stock_watchlists')
    op.drop_index(op.f('ix_stock_watchlists_stock_id'), table_name='stock_watchlists')
    op.drop_index(op.f('ix_stock_watchlists_user_id'), table_name='stock_watchlists')
    op.alter_column('token_usage_logs', 'user_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
    op.alter_column('transactions', 'is_recurring',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('transactions', 'expense_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('transactions', 'created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('transactions', 'updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('transactions', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('transactions', 'expense_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('transactions', 'is_recurring',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('token_usage_logs', 'user_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
    op.create_index(op.f('ix_stock_watchlists_user_id'), 'stock_watchlists', ['user_id'], unique=False)
    op.create_index(op.f('ix_stock_watchlists_stock_id'), 'stock_watchlists', ['stock_id'], unique=False)
    op.create_index(op.f('ix_stock_watchlists_category_id'), 'stock_watchlists', ['category_id'], unique=False)
    op.drop_index(op.f('ix_card_statements_id'), table_name='card_statements')
    op.alter_column('card_statements', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('card_statements', 'processed_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
    op.alter_column('card_statements', 'uploaded_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('card_statements', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.create_table('overspending_items',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('summary_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('month', mysql.VARCHAR(length=7), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('category_amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('category_ratio', mysql.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('overspending_threshold', mysql.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('previous_category_amount', mysql.DECIMAL(precision=15, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('spending_change_rate', mysql.DECIMAL(precision=6, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('reason', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['monthly_spending_summaries.id'], name=op.f('overspending_items_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('overspending_items_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_uca1400_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_agent_chat_messages_user_id'), table_name='agent_chat_messages')
    op.drop_index(op.f('ix_agent_chat_messages_session_id'), table_name='agent_chat_messages')
    op.drop_table('agent_chat_messages')
    op.drop_index(op.f('ix_agent_chat_sessions_user_id'), table_name='agent_chat_sessions')
    op.drop_table('agent_chat_sessions')
    # ### end Alembic commands ###
