"""add market cap and listed shares to stock prices

Revision ID: 76458807650c
Revises: 79932b99326a
Create Date: 2026-06-22 18:24:17.329168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76458807650c'
down_revision: Union[str, Sequence[str], None] = '79932b99326a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_prices', sa.Column('listed_shares', sa.BigInteger(), server_default=sa.text('0'), nullable=True))
    op.add_column('stock_prices', sa.Column('market_cap', sa.DECIMAL(precision=25, scale=2), server_default=sa.text('0'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_prices', 'market_cap')
    op.drop_column('stock_prices', 'listed_shares')
    # ### end Alembic commands ###
