"""sync schema with table design

Revision ID: 79932b99326a
Revises: 9ed569ee2202
Create Date: 2026-06-19 16:19:09.602001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '79932b99326a'
down_revision: Union[str, Sequence[str], None] = '9ed569ee2202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_title', sa.String(length=100), nullable=False),
    sa.Column('market_summary', sa.Text(), nullable=True),
    sa.Column('sector_summary', sa.Text(), nullable=True),
    sa.Column('watchlist_summary', sa.Text(), nullable=True),
    sa.Column('risk_summary', sa.Text(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_report_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('current_price', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('change_rate', sa.DECIMAL(precision=6, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('news_summary', sa.Text(), nullable=True),
    sa.Column('sector_summary', sa.Text(), nullable=True),
    sa.Column('risk_factors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['stock_reports.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('insurance_analyses')
    op.add_column('deposit_products', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('deposit_products', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.add_column(
    "finance_profiles",
    sa.Column(
        "monthly_salary",
        sa.DECIMAL(15, 2),
        nullable=False,
        server_default="0"
    )
)
    op.add_column('finance_profiles', sa.Column('annual_salary', sa.DECIMAL(precision=15, scale=2), nullable=False))
    op.add_column('finance_profiles', sa.Column('fixed_expense', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=True))
    op.add_column(
    "finance_profiles",
    sa.Column(
        "risk_type",
        sa.String(length=30),
        nullable=False,
        server_default="MODERATE"
    )
)
    op.add_column('finance_profiles', sa.Column('investment_goal', sa.String(length=100), nullable=True))
    op.add_column('finance_profiles', sa.Column('target_saving_amount', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=True))
    op.create_unique_constraint(None, 'finance_profiles', ['user_id'])
    op.drop_column('finance_profiles', 'financial_goal')
    op.drop_column('finance_profiles', 'investment_type')
    op.drop_column('finance_profiles', 'income_level')
    op.drop_column('finance_profiles', 'age_group')
    op.add_column('financial_product_recommendations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('financial_product_recommendations', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.add_column('insurance_products', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('interest_calculation_histories', sa.Column('maturity_amount', sa.BigInteger(), nullable=False))
    op.add_column('interest_calculation_histories', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('interest_calculation_histories', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.add_column('news_sector_mappings', sa.Column('matched_keywords', sa.JSON(), nullable=True))
    op.add_column('news_summaries', sa.Column('one_line_summary', sa.String(length=500), nullable=True))
    op.add_column('news_summaries', sa.Column('summary_text', sa.Text(), nullable=False))
    op.add_column('news_summaries', sa.Column('positive_factors', sa.JSON(), nullable=True))
    op.add_column('news_summaries', sa.Column('risk_factors', sa.JSON(), nullable=True))
    op.add_column('news_summaries', sa.Column('investment_note', sa.Text(), nullable=True))
    op.add_column('news_summaries', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.drop_column('news_summaries', 'keywords')
    op.drop_column('news_summaries', 'summary')
    op.drop_column('news_summaries', 'investment_view')
    op.add_column('oauth_accounts', sa.Column('provider_email', sa.String(length=255), nullable=False))
    op.add_column('oauth_accounts', sa.Column('access_token', sa.Text(), nullable=True))
    op.add_column('oauth_accounts', sa.Column('refresh_token', sa.Text(), nullable=True))
    op.add_column('oauth_accounts', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('refresh_token', sa.Text(), nullable=False))
    op.add_column('refresh_tokens', sa.Column('expires_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('refresh_tokens', 'token',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.add_column('saving_products', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('saving_products', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.add_column('sector_insights', sa.Column('news_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('sector_insights', sa.Column('positive_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('sector_insights', sa.Column('neutral_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('sector_insights', sa.Column('negative_count', sa.Integer(), server_default=sa.text('0'), nullable=True))
    op.add_column('sector_insights', sa.Column('main_keywords', sa.JSON(), nullable=True))
    op.add_column('sector_insights', sa.Column('insight_summary', sa.Text(), nullable=True))
    op.drop_column('sector_insights', 'keywords')
    op.drop_column('sector_insights', 'trend_summary')
    op.add_column('stock_news_mappings', sa.Column('matched_keyword', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=500), nullable=True))
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('users', 'role')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('users', sa.Column('role', mysql.VARCHAR(length=20), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('users', 'profile_image_url')
    op.drop_column('stock_news_mappings', 'matched_keyword')
    op.add_column('sector_insights', sa.Column('trend_summary', mysql.TEXT(), nullable=True))
    op.add_column('sector_insights', sa.Column('keywords', mysql.TEXT(), nullable=True))
    op.drop_column('sector_insights', 'insight_summary')
    op.drop_column('sector_insights', 'main_keywords')
    op.drop_column('sector_insights', 'negative_count')
    op.drop_column('sector_insights', 'neutral_count')
    op.drop_column('sector_insights', 'positive_count')
    op.drop_column('sector_insights', 'news_count')
    op.alter_column('saving_products', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_column('saving_products', 'created_at')
    op.alter_column('refresh_tokens', 'token',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.drop_column('refresh_tokens', 'expires_at')
    op.drop_column('refresh_tokens', 'refresh_token')
    op.drop_column('oauth_accounts', 'token_expires_at')
    op.drop_column('oauth_accounts', 'refresh_token')
    op.drop_column('oauth_accounts', 'access_token')
    op.drop_column('oauth_accounts', 'provider_email')
    op.add_column('news_summaries', sa.Column('investment_view', mysql.TEXT(), nullable=True))
    op.add_column('news_summaries', sa.Column('summary', mysql.TEXT(), nullable=False))
    op.add_column('news_summaries', sa.Column('keywords', mysql.TEXT(), nullable=True))
    op.drop_column('news_summaries', 'model_name')
    op.drop_column('news_summaries', 'investment_note')
    op.drop_column('news_summaries', 'risk_factors')
    op.drop_column('news_summaries', 'positive_factors')
    op.drop_column('news_summaries', 'summary_text')
    op.drop_column('news_summaries', 'one_line_summary')
    op.drop_column('news_sector_mappings', 'matched_keywords')
    op.alter_column('interest_calculation_histories', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_column('interest_calculation_histories', 'updated_at')
    op.drop_column('interest_calculation_histories', 'maturity_amount')
    op.drop_column('insurance_products', 'created_at')
    op.alter_column('financial_product_recommendations', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_column('financial_product_recommendations', 'updated_at')
    op.add_column('finance_profiles', sa.Column('age_group', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('finance_profiles', sa.Column('income_level', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('finance_profiles', sa.Column('investment_type', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('finance_profiles', sa.Column('financial_goal', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'finance_profiles', type_='unique')
    op.drop_column('finance_profiles', 'target_saving_amount')
    op.drop_column('finance_profiles', 'investment_goal')
    op.drop_column('finance_profiles', 'risk_type')
    op.drop_column('finance_profiles', 'fixed_expense')
    op.drop_column('finance_profiles', 'annual_salary')
    op.drop_column('finance_profiles', 'monthly_salary')
    op.alter_column('deposit_products', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_column('deposit_products', 'created_at')
    op.create_table('insurance_analyses',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('recommended_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('analysis_result', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('1')),
    sa.PrimaryKeyConstraint('id'),
    mariadb_collate='utf8mb4_uca1400_ai_ci',
    mariadb_default_charset='utf8mb4',
    mariadb_engine='InnoDB'
    )
    op.drop_table('stock_report_items')
    op.drop_table('stock_reports')
    # ### end Alembic commands ###
