"""add company_code to insurance_products

Revision ID: 86369419f544
Revises: 54aae840dcb3
Create Date: 2026-07-13 14:07:39.580659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '86369419f544'
down_revision: Union[str, Sequence[str], None] = '54aae840dcb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('insurance_products', sa.Column('company_code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurance_products', 'company_code')
    # ### end Alembic commands ###
