"""initial tables

Revision ID: 9ed569ee2202
Revises: 
Create Date: 2026-06-18 16:44:05.591051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed569ee2202'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deposit_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('interest_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('max_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('join_period', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('insurance_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('insurance_name', sa.String(length=200), nullable=False),
    sa.Column('insurance_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_link', sa.String(length=1000), nullable=True),
    sa.Column('api_link', sa.String(length=1000), nullable=True),
    sa.Column('url_hash', sa.String(length=64), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('search_keyword', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    op.create_table('saving_products',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('interest_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('max_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('join_period', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('stock_sectors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sector_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_name')
    )
    op.create_table('stocks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False),
    sa.Column('stock_name', sa.String(length=100), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('representative_sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code')
    )
    op.create_table('token_limit_settings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('daily_token_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('login_type', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('card_statements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('card_name', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('income_level', sa.String(length=50), nullable=True),
    sa.Column('investment_type', sa.String(length=50), nullable=True),
    sa.Column('financial_goal', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_product_recommendations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_type', sa.String(length=30), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_analyses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('recommended_type', sa.String(length=50), nullable=False),
    sa.Column('analysis_result', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interest_calculation_histories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('principal', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('before_tax_amount', sa.BigInteger(), nullable=False),
    sa.Column('after_tax_amount', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_spending_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_income', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('monthly_salary', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total_spending', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('fixed_expense', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('variable_expense', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('remaining_money', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('spending_diff', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('spending_change_rate', sa.DECIMAL(precision=6, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', name='uk_monthly_summary_user_month')
    )
    op.create_table('news_sector_mappings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.BigInteger(), nullable=False),
    sa.Column('sector_id', sa.BigInteger(), nullable=False),
    sa.Column('relevance_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['stock_sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id', 'sector_id', name='uk_news_sector_mapping')
    )
    op.create_table('news_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('investment_view', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sector_insights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sector_id', sa.BigInteger(), nullable=False),
    sa.Column('insight_date', sa.Date(), nullable=False),
    sa.Column('period_days', sa.BigInteger(), nullable=False),
    sa.Column('issue_score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('risk_summary', sa.Text(), nullable=True),
    sa.Column('trend_summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['stock_sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', 'insight_date', 'period_days', name='uk_sector_insight_period')
    )
    op.create_table('sector_keywords',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sector_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['stock_sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_id', 'keyword', name='uk_sector_keyword')
    )
    op.create_table('stock_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=True),
    sa.Column('news_id', sa.BigInteger(), nullable=True),
    sa.Column('sector_id', sa.BigInteger(), nullable=True),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['stock_sectors.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_news_mappings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('news_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('relevance_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id', 'stock_id', name='uk_news_stock_mapping')
    )
    op.create_table('stock_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('previous_close', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('price_change', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('change_rate', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('open_price', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('high_price', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('low_price', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('trade_value', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'price_date', 'source', name='uk_stock_price_date_source')
    )
    op.create_table('stock_sector_mappings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('sector_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sector_id'], ['stock_sectors.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'sector_id', name='uk_stock_sector_mapping')
    )
    op.create_table('stock_watchlists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stock_id', sa.BigInteger(), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('alert_price', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'stock_id', name='uk_watchlist_user_stock')
    )
    op.create_table('token_usage_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('feature_type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('embedding_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.DECIMAL(precision=12, scale=6), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('summary_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('report_title', sa.String(length=100), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('category_text', sa.Text(), nullable=True),
    sa.Column('overspending_text', sa.Text(), nullable=True),
    sa.Column('card_text', sa.Text(), nullable=True),
    sa.Column('compare_text', sa.Text(), nullable=True),
    sa.Column('recommendation_text', sa.Text(), nullable=True),
    sa.Column('agent_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['monthly_spending_summaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summary_id')
    )
    op.create_table('card_spendings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('summary_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('card_name', sa.String(length=50), nullable=False),
    sa.Column('card_amount', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('card_ratio', sa.DECIMAL(precision=6, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('transaction_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['monthly_spending_summaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summary_id', 'card_name', name='uk_card_spending_summary_card')
    )
    op.create_table('category_spendings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('summary_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('category_amount', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('category_ratio', sa.DECIMAL(precision=6, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('transaction_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('previous_category_amount', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('spending_diff', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('spending_change_rate', sa.DECIMAL(precision=6, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['monthly_spending_summaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summary_id', 'category', name='uk_category_spending_summary_category')
    )
    op.create_table('chatbot_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_type', sa.String(length=30), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('agent_response', sa.Text(), nullable=False),
    sa.Column('referenced_summary_id', sa.BigInteger(), nullable=True),
    sa.Column('referenced_stock_id', sa.BigInteger(), nullable=True),
    sa.Column('referenced_news_id', sa.BigInteger(), nullable=True),
    sa.Column('referenced_sector_id', sa.BigInteger(), nullable=True),
    sa.Column('referenced_recommendation_id', sa.BigInteger(), nullable=True),
    sa.Column('used_tools', sa.Text(), nullable=True),
    sa.Column('disclaimer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['referenced_news_id'], ['news_articles.id'], ),
    sa.ForeignKeyConstraint(['referenced_recommendation_id'], ['financial_product_recommendations.id'], ),
    sa.ForeignKeyConstraint(['referenced_sector_id'], ['stock_sectors.id'], ),
    sa.ForeignKeyConstraint(['referenced_stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['referenced_summary_id'], ['monthly_spending_summaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overspending_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('summary_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('category_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('category_ratio', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('overspending_threshold', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('previous_category_amount', sa.DECIMAL(precision=15, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('spending_change_rate', sa.DECIMAL(precision=6, scale=2), server_default=sa.text('0'), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['summary_id'], ['monthly_spending_summaries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('statement_id', sa.BigInteger(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('merchant_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('expense_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['card_statements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('overspending_items')
    op.drop_table('chatbot_messages')
    op.drop_table('category_spendings')
    op.drop_table('card_spendings')
    op.drop_table('analysis_reports')
    op.drop_table('token_usage_logs')
    op.drop_table('stock_watchlists')
    op.drop_table('stock_sector_mappings')
    op.drop_table('stock_prices')
    op.drop_table('stock_news_mappings')
    op.drop_table('stock_alerts')
    op.drop_table('sector_keywords')
    op.drop_table('sector_insights')
    op.drop_table('refresh_tokens')
    op.drop_table('oauth_accounts')
    op.drop_table('news_summaries')
    op.drop_table('news_sector_mappings')
    op.drop_table('monthly_spending_summaries')
    op.drop_table('interest_calculation_histories')
    op.drop_table('insurance_analyses')
    op.drop_table('financial_product_recommendations')
    op.drop_table('finance_profiles')
    op.drop_table('card_statements')
    op.drop_table('users')
    op.drop_table('token_limit_settings')
    op.drop_table('stocks')
    op.drop_table('stock_sectors')
    op.drop_table('saving_products')
    op.drop_table('news_articles')
    op.drop_table('insurance_products')
    op.drop_table('deposit_products')
    # ### end Alembic commands ###
