from app.models.user_model import *
from app.models.card_statement_model import *
from app.models.transaction_model import *
from app.models.spending_analysis_model import *
from app.models.financial_product_model import *
from app.models.stock_model import *
from app.models.news_model import *
from app.models.chatbot_model import *
from app.models.alert_model import *
from app.models.admin_model import *